### ISSUE TITLE
Change time format

### ISSUE THREAD

**Issue by Glaived** [breeku/opentrackmania#24]
For `m`:`ss`.`SSS` format

e.g. :
- 0:39.534
- 1:56.503 (1 minutes 56 secondes)
- 12:21.816 (12 minutes 21 secondes)
- 62:25.564 (1 hour, 2 minutes, 25 secondes)

**Comment by breeku** [comment]
Not sure if it's better like 0:39.534 or 00:39.534, in the game its the latter so I changed to that. May be clearer in the shorter form though since maps rarely go above 10min

Well it's easy to change.
