### ISSUE TITLE
Expired cert for api.opentrackmania.com

### ISSUE THREAD

**Issue by KemTM** [breeku/opentrackmania#38]
Looks like the Let's Encrypt cert issued for api.opentrackmania.com has expired.
![image](https://user-images.githubusercontent.com/7620234/99013975-5ba8b700-255a-11eb-8804-a0295ccd6032.png)

It also appears that you use two different certs for the frontend ant the API backend.

Not sure what you're using, but I suggest getting one cert for both services (via certbot dns challenge or the likes)

**Comment by breeku** [comment]
Hey, thanks for the issue

I had forgotten to add cron job for the cert, I fixed that
